export const POST_REPOSITORY = 'POST_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const COMMENT_REPOSITORY = 'COMMENT_REPOSITORY';
export const VOTE_REPOSITORY = 'LIKE_REPOSITORY';
export const REPLAY_REPOSITORY = 'REPLAY_REPOSITORY';
export const SEQUELIZE = 'SEQUELIZE';
